# Generated by Django 4.0.2 on 2022-02-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('retake', models.IntegerField()),
                ('time', models.CharField(max_length=50)),
                ('remote', models.IntegerField()),
                ('price', models.IntegerField()),
                ('QR', models.IntegerField()),
            ],
        ),
    ]
