# Generated by Django 4.0.2 on 2022-02-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='liked_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
