# Generated by Django 4.0.2 on 2022-02-20 16:32

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('operationHour', models.CharField(max_length=50)),
                ('x', models.CharField(max_length=50)),
                ('y', models.CharField(max_length=50)),
                ('street', models.IntegerField(default=0)),
                ('deco', models.CharField(max_length=50)),
                ('iron', models.IntegerField(default=0)),
                ('boxnum', models.IntegerField(default=0)),
                ('rate_average', models.FloatField(default=0)),
                ('likenum', models.IntegerField(default=0)),
                ('review_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolike', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('content', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='Review')),
                ('boothid', models.IntegerField()),
                ('rate', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('tag', multiselectfield.db.fields.MultiSelectField(choices=[('시설이 깨끗해요', '시설이 깨끗해요'), ('소품이 다양해요', '소품이 다양해요'), ('부스가 많아요', '부스가 많아요'), ('고데기가 있어요', '고데기가 있어요'), ('로드점이에요', '로드점이에요')], max_length=41)),
                ('color', multiselectfield.db.fields.MultiSelectField(choices=[('핑크', '핑크'), ('하늘', '하늘'), ('노랑', '노랑'), ('회색', '회색'), ('남색', '남색'), ('연두', '연두'), ('보라', '보라'), ('빨강', '빨강'), ('주황', '주황'), ('기타', '기타')], max_length=29)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.booth')),
            ],
        ),
    ]
