# Generated by Django 4.0.2 on 2022-02-07 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand'),
        ),
    ]
