# Generated by Django 4.0.2 on 2022-02-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booth',
            old_name='rating',
            new_name='rate_average',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='review',
            name='boothid',
            field=models.IntegerField(),
        ),
    ]
