# Generated by Django 4.0.2 on 2022-02-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_booth_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='operationHour',
            field=models.CharField(max_length=50),
        ),
    ]
