# Generated by Django 4.0.2 on 2022-02-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_rename_rating_booth_rate_average_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='date',
            new_name='time',
        ),
    ]
