# Generated by Django 4.0.2 on 2022-02-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_booth_operationhour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booth',
            name='type',
        ),
    ]
